migrateup:
	migrate -path migrations -database "mysql://test:test@(localhost:3306)/api" -verbose up

migratedown:
	migrate -path migrations -database "mysql://test:test@(localhost:3306)/api" -verbose down	